FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

ADD https://storage.yandexcloud.net/hackathon-perm-2026/faiss_flat_(metric%3Dip)__intfloat_multilingual-e5-small.index  ./models/

RUN apt-get update && \
    apt-get install -y --no-install-recommends build-essential && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt ./requirements.txt

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 95

CMD ["uvicorn", "src.api.search_api:app", "--host", "0.0.0.0", "--port", "95"]

